import I18n from '../i18n/i18n';

export const HelperSteps = [
  {
    step: 0,
    active: false,
    id: 'first-product',
    info: I18n.t('helperStep.firstProduct.info'),
    icon: 'box-stock',
    completed: false,
    completionDate: null,
    routeName: 'ProductDetail',
    stackName: 'CurrentSale',
    cta: I18n.t('helperStep.firstProduct.cta'),
  },
  {
    step: 1,
    active: true,
    id: 'first-sale',
    info: I18n.t('helperStep.firstSale.info'),
    icon: 'check-in',
    completed: false,
    completionDate: null,
    routeName: 'CurrentSale',
    stackName: '',
    cta: I18n.t('helperStep.firstSale.cta'),
  },
  {
    step: 2,
    active: true,
    id: 'first-customer',
    info: I18n.t('helperStep.firstCustomer.info'),
    icon: 'person',
    completed: false,
    completionDate: null,
    routeName: 'CustomerCreate',
    stackName: 'Customers',
    cta: I18n.t('helperStep.firstCustomer.cta'),
  },
  {
    step: 3,
    active: true,
    id: 'config-receipt',
    info: I18n.t('helperStep.configReceipt.info'),
    icon: 'receipt-complete',
    completed: false,
    completionDate: null,
    routeName: 'ConfigReceipt',
    stackName: 'Config',
    cta: I18n.t('helperStep.configReceipt.cta'),
  },
  {
    step: 4,
    active: true,
    id: 'publish-catalog',
    info: I18n.t('helperStep.publishCatalog.info'),
    icon: 'cart',
    completed: false,
    completionDate: null,
    routeName: 'OnlineCatalog',
    stackName: '',
    cta: I18n.t('helperStep.publishCatalog.cta'),
  },
  {
    step: 5,
    active: true,
    id: 'invite-users',
    info: I18n.t('helperStep.inviteUsers.info'),
    icon: 'users',
    completed: false,
    completionDate: null,
    routeName: 'Users',
    stackName: '',
    cta: I18n.t('helperStep.inviteUsers.cta'),
  },
  {
    step: 6,
    active: true,
    id: 'sale-credit',
    info: I18n.t('helperStep.saleCredit.info'),
    icon: 'users',
    completed: false,
    completionDate: null,
    routeName: 'StorePreferences',
    stackName: 'Config',
    cta: I18n.t('helperStep.saleCredit.cta'),
  },
  {
    step: 7,
    active: true,
    id: 'share-catalog',
    info: I18n.t('helperStep.shareCatalog.info'),
    icon: 'share',
    completed: false,
    completionDate: null,
    routeName: 'OnlineCatalog',
    stackName: '',
    cta: I18n.t('helperStep.shareCatalog.cta'),
  }
  
];
