export * from './Breakpoints'
export * from './CurrentSaleDiscountType'
export * from './CustomerAccountMovementReason'
export * from './CustomerAccountMovementType'
export * from './CustomerOrigin'
export * from './DetailOrigin'
export * from './Features'
export * from './LinkingMap'
export * from './ErrorTypes'
export * from './FirebaseAnalytics'
export * from './OnboardingCarousel'
export * from './MercadoPagoPaymentType'
export * from './OrderStatus'
export * from './InstallmentType'
export * from './HelperSteps'
export * from './HelperStepsStates'
export * from './NotificationsSnapshot'
export * from './ProductTabKeys'
export * from './PaymentDetailType'
export * from './Period'
export * from './PaymentGatewayType'
export * from './PaymentGatewayServiceType'
export * from './Permission'
export * from './Plans'
export * from './PaymentType'
export * from './PROFeatures'
export * from './RemoteConfigDefaults'
export * from './SaleOrigin'
export * from './StockHistoryType'
export * from './TaxType'
export * from './UserPermission'
export * from './Flavors'
export * from './Catalog'
export * from './Screens'
export * from './Subscription.ts'

export const toList = (obj) => {
	if (!Object.prototype.hasOwnProperty.call(obj, 'items')) {
		return []
	}
	return Object.keys(obj.items).map((key) => obj.items[key])
}
