export const LinkingMap = {
	MERCADOPAGO_PAYMENT: 0,
	CONFIRM_ACCOUNT: 1,
	ACCOUNT_CONFIRMED: 2,
	CONFIG: 3,
	CONFIG_CARD_SERVICE: 4,
	items: [
		{ key: 'mercadopago', routes: {} },
		{ key: 'confirm-account', routes: { stack: 'Confirmation', route: 'AccountConfirmation' } },
		{ key: 'account-confirmed', routes: { stack: 'Confirmation', route: 'PageConfirmation' } },
		{ key: 'config', routes: { stack: 'Config', route: 'ConfigContainer' } },
		{ key: 'config/card-service', routes: { stack: 'Config', route: 'ConfigCardService' } },
		{key: 'catalog-payments', routes: {stack: 'OnlineCatalog', route: 'CatalogOrderPayments'}},
	],
}

export const oneSignalRoutesMap = {
	currentSale: ['CurrentSale'],
	orders: ['OpenedSales'],
	products: ['Products'],
	onlineCatalog: ['OnlineCatalog'],
	customers: ['Customers'],
	sales: ['Sales'],
	statistics: ['Statistics'],
	users: ['Users'],
	config: ['Config'],
	helpcenter: ['Helpcenter'],
	billing: ['Plans'],
	customerCreate: ['CustomerCreate'],
	productCreate: ['CurrentSale', 'ProductDetail'],
	redirectWeb: ['Plans', 'RedirectCheckoutWebContainer'],
	socialMediaIntegration: ['Config', 'SocialMediaIntegration'],
	instagramShopping: ['Config', 'InstagramPage'],
	fbeFood: ['Config', 'FBEPage'],
	facebookPixel: ['Config', 'FacebookPixelPage'],
	googleShopping: ['Config', 'GoogleShoppingPage'],
	tiktokPage: ['Config', 'TiktokPage'],
	generalPreferences: ['Config', 'StorePreferences'],
	businessInformation: ['Config', 'StoreDetailContainer'],
	integratedPayments: ['Config', 'ConfigIntegratedPayments'],
	salesTaxes: ['Config', 'Taxes'],
	shippingFees: ['Config', 'ShippingFees'],
	exportReports: ['Config', 'DataExport'],
}
