// INITIALIZER
export const INITIALIZER = 'initilizer'

// LOGIN / AUTH // INITIALIZER
export const LOGIN_SUCCESS = 'login_success'
export const LOGIN_FAIL = 'login_Fail'
export const LOGOUT = 'logout'
export const SET_MULTI_USERS = 'set_multi_users'
export const SET_SIGNIN_EMAIL = 'set_signin_email'
export const SET_SIGNIN_PASSWORD = 'set_signin_password'
export const SET_AUTH_CONFIRMED = 'set_auth_confirmed'
export const SET_CAMPAIGN_PROPS = 'set_campaign_props'
export const USER_SET = 'user_set'
export const ACCOUNT_STORE_SAVE = 'account_store_save'
export const PIX_DATA_CONFIG = 'pix_data_config'
export const ACCOUNT_TAX_SAVE = 'account_tax_save'
export const CATALOG_TAX_SAVE = 'catalog_tax_save'
export const STORE_IMAGE_SET = 'store_image_set'
export const ADD_USER_FAIL = 'add_user_fail'
export const SET_DID = 'set_did'
export const ACCOUNT_INTEGRATION_PARTNER = 'account_integration_partner'
export const UPDATE_USER_ACCOUNT = 'update_user_account'
export const AUTH_INITIALIZE = 'auth_initialize'
export const TAXES_FETCH = 'taxes_fetch'
export const TAXES_CLEAR = 'taxes_clear'
export const SET_USER_CUSTOM_INFO = 'set_user_custom_info'
export const SET_KID_IN_AUTH = 'set_kid_in_auth'
export const LOADING_AUTHENTICATION = 'loading_authentication'

// PREFERENCE
export const PREFERENCE_SET = 'preference_set'
export const PREFERENCES_FETCH = 'preference_fetch'

// SYNC
export const SYNC_DOWN_CHANGE = 'sync_down_change'
export const SYNC_RESET = 'sync_reset'
export const SYNC_DOWN_RESTORE = 'sync_down_restore'
export const SYNC_LOGOUT = 'sync_logout'
export const SYNC_SET_IS_FIRST_NOTIFICATION = 'sync_set_is_first_notification'
export const SET_SYNCING_SALES_MAP = 'set_syncing_sales_map'

// CURRENT SALE
export const CURRENT_SALE_SET_OPENED_SALE = 'current_sale_set_opened_sale'
export const CURRENT_SALE_ADD_ITEM = 'current_sale_add_item'
export const CURRENT_SALE_REMOVE_ITEM = 'current_sale_remove_item'
export const CURRENT_SALE_UPDATE_ITEM = 'current_sale_update_item'
export const CURRENT_SALE_ADD_CUSTOMER = 'current_sale_add_customer'
export const CURRENT_SALE_REMOVE_CUSTOMER = 'current_sale_remove_customer'
export const CURRENT_SALE_ADD_PAYMENT = 'current_sale_add_payment'
export const CURRENT_SALE_SPLIT_PAYMENT = 'current_sale_split_payment'
export const CURRENT_SALE_REMOVE_PAYMENT = 'current_sale_remove_payment'
export const CURRENT_SALE_PAYMENT_RENEW = 'current_sale_payment_renew'
export const CURRENT_SALE_ADD_OBSERVATION = 'current_sale_add_observation'
export const CURRENT_SALE_ADD_DESCRIPTION = 'current_sale_add_description'
export const CURRENT_SALE_SET_STATUS = 'current_sale_set_status'
export const CURRENT_SALE_DISCOUNT = 'current_sale_discount'
export const CURRENT_SALE_REMOVE_DISCOUNT = 'current_sale_remove_discount'
export const CURRENT_SALE_RENEW = 'current_sale_renew'
export const CURRENT_SALE_SAVE_TO_STORAGE = 'current_sale_save_to_storage'
export const CURRENT_SALE_RETRIEVE_DATA = 'current_sale_retrieve_data'
export const CURRENT_SALE_SET_IN_SPLIT_PAYMENT = 'current_sale_set_in_split_payment'
export const CURRENT_SALE_SET_TAX = 'current_sale_set_tax'
export const CURRENT_SALE_SET_OPTIONAL_TAX = 'current_sale_set_optional_tax'
export const CURRENT_SALE_SET_SHIPPING_FEE = 'current_sale_set_shipping_fee'
export const CURRENT_SALE_SET = 'current_sale_set'
export const LAST_SALE_SET = 'last_sale_set'
export const CLEAR_LAST_SALE = 'clear_last_sale'
export const CURRENT_SALE_SET_TOTAL_PAY = 'current_sale_set_total_pay'
export const CURRENT_SALE_SET_TOTAL_PAID = 'current_sale_set_total_paid'
export const CURRENT_SALE_RESET_PAID_VALUES = 'current_sale_reset_paid_values'
export const CURRENT_SALE_CLEAR_ACCOUNT_PAYMENTS = 'current_sale_clear_account_payments'

// SALE
export const SALES_FETCH = 'sales_fetch'
export const ORDERS_FETCH = 'orders_fetch'
export const SALES_FETCH_BY_CUSTOMER = 'sales_fetch_by_customer'
export const ORDERS_FETCH_BY_CUSTOMER = 'orders_fetch_by_customer'
export const SALES_FETCH_BY_USER = 'sales_fetch_by_user'
export const SALE_UPDATE_ITEM = 'sale_update_item'
export const SALE_UPDATE_COUNTERS = 'sale_update_counters'
export const SALE_REMOVE = 'sale_remove'
export const SALE_DETAIL = 'sale_detail'
export const SALES_CLEAR = 'sales_clear'
export const SALES_CLEAR_DETAIL = 'sales_clear_detail'
export const SALES_SET_FILTER = 'sales_set_filter'
export const ORDERS_SET_FILTER = 'order_set_filter'
export const SALES_REPLACE_FILTER = 'sales_replace_filter'
export const SALES_CLEAR_FILTER = 'sales_clear_filter'
export const SALES_UPDATE_QUANTITY_OPENED = 'sales_update_quantity_opened'
export const SALES_UPDATE_QUANTITY_CLOSED = 'sales_update_quantity_closed'
export const SALES_UPDATE_SELECTED_USERS_HISTORY = 'sales_update_selected_users_history'
export const SALES_UPDATE_SEARCH_TERM = 'sales_update_search_term'
export const SALES_UPDATE_LIST_ITEM = 'sales_update_list_item'
export const SALES_UPDATE_QUANTITY = 'sales_update_quantity'
export const SALES_LAST_NUMBER = 'sales_last_number'
export const SALES_SET_FILTER_TYPE = 'sales_set_filter_type'
export const SALE_SAVE_WITH_PAYMENT_LINK = 'sale_save_with_payment_link'
export const SALE_GENERATE_PAYMENT_LINK = 'sale_generate_payment_link'
export const SALES_RESET_LIST_SIZE = 'sales_reset_list_size'
export const SALES_SET_EXPANDED_ITEMS = 'sales_set_expanded_items'
export const SALES_RESET_GROUP = 'sales_reset'
export const SALE_UPDATE_UNSYCED_SALES = 'sale_update_unsyced_sales'
export const SALES_SET_THIS_MONTH = 'sales_set_this_month'

// PRODUCT
export const PRODUCTS_FETCH = 'products_fetch'
export const PRODUCTS_LIST_FETCH = 'products_list_fetch'
export const PRODUCTS_LIST_SERVER_FETCH = 'products_list_server_fetch'
export const SET_SELECTED_VARIATION_FOR_PHOTO_EDIT = 'set_selected_variation_for_photo_edit'
export const PRODUCTS_LIST_SERVER_FETCH_ERROR = 'products_list_server_fetch_error'
export const PRODUCTS_SET_SEARCH_TEXT = 'products_set_search_text'
export const PRODUCT_SAVE = 'product_save'
export const PRODUCT_SAVE_BY_QUICKSALE = 'product_save_by_quicksale'
export const PRODUCT_DETAIL = 'product_detail'
export const PRODUCT_REMOVE = 'product_remove'
export const PRODUCT_MANAGEMENT_SET_VALUE = 'product_management_set_value'
export const PRODUCT_STOCK_HISTORY_SET_FILTER = 'product_stock_history_set_filter'
export const PRODUCT_STOCK_HISTORY_CLEAR_FILTER = 'product_stock_history_clear_filter'
export const PRODUCT_MANAGEMENT_RESET = 'product_management_reset'
export const PRODUCT_MANAGE_STOCK = 'product_manage_stock'
export const PRODUCT_MANAGE_STOCK_ACTIVITY = 'product_manage_stock_activity'
export const PRODUCTS_CLEAR = 'products_clear'
export const PRODUCTS_UPDATE_QUANTITY = 'products_update_quantity'
export const PRODUCT_GET_STOCK_HISTORY = 'product_get_stock_history'
export const PRODUCT_FILTER_STOCK_HISTORY = 'product_filter_stock_history'
export const PRODUCT_SORT_TYPE_SET = 'product_sort_type_set'
export const PRODUCT_SET_VIRTUAL_DATA = 'product_set_virtual_data'
export const PRODUCT_AI_PRODUCT_DESCRIPTION = 'product_ai_product_description'
export const PRODUCT_AI_IMAGE_SUGGESTIONS = 'product_ai_image_suggestions'
export const CLEAR_PRODUCT_AI_SUGGESTIONS = 'clear_product_ai_suggestions'
export const PRODUCT_AI_SUGGESTIONS_APPLIED = 'product_ai_suggestions_applied'
export const UPDATE_SHARE_CATALOG_MODAL_VISIBILITY = 'update_share_catalog_modal_visibility'

// CUSTOMER
export const CUSTOMERS_FETCH = 'customers_fetch'
export const CUSTOMERS_FETCH_STATEMENTS = 'customers_fetch_statements'
export const CUSTOMER_SAVE = 'customer_save'
export const CUSTOMER_DETAIL = 'customer_detail'
export const CUSTOMER_DETAIL_SET_LOADING = 'customer_detail_set_loading'
export const CUSTOMER_REMOVE = 'customer_remove'
export const CUSTOMER_MANAGE_NEW_BALANCE = 'customer_manage_new_balance'
export const CUSTOMER_MANAGE_ACTUAL_BALANCE = 'customer_manage_actual_balance'
export const CUSTOMER_ACCOUNT_EDIT_BALANCE = 'customer_account_edit_balance'
export const CUSTOMER_ACCOUNT_RESET_BALANCE = 'customer_account_reset_balance'
export const CUSTOMER_ACCOUNT_UPDATE_BALANCE = 'customer_account_update_balance'
export const CUSTOMER_ACCOUNT_EDIT_PAYMENT = 'customer_account_edit_payment'
export const CUSTOMER_ACCOUNT_GET_STATEMENTS = 'customer_account_get_statements'
export const CUSTOMERS_CLEAR = 'customers_clear'
export const CUSTOMERS_GET_CONTACTS = 'customers_get_contacts'
export const CUSTOMERS_SELECT_CONTACT = 'customers_select_contact'
export const CUSTOMERS_SELECT_ALL_CONTACTS = 'customers_select_all_contacts'
export const CUSTOMERS_CLEAN_CONTACTS = 'customers_clean_contacts'
export const CUSTOMERS_ACCOUNT_GENERAL_FILTER_SET = 'customers_general_filter_set'
export const CUSTOMERS_ACCOUNT_GENERAL_FILTER_CLEAR = 'customers_general_filter_clear'
export const CUSTOMERS_ACCOUNT_FILTER_SET = 'customers_filter_set'
export const CUSTOMERS_ACCOUNT_FILTER_CLEAR = 'customers_account_filter_clear'
export const CUSTOMERS_FILTER_TABS_SET = 'customers_filter_tabs_set'
export const CUSTOMERS_SET_BALANCE_TOTALS = 'customers_set_balance_totals'
export const CUSTOMER_ACCOUNT_CANCEL_STATEMENT = 'customer_account_cancel_statement'

// STORE
export const STORE_FETCH = 'store_fetch'
export const STORE_SAVE = 'store_save'
export const STORE_IMAGE_URL = 'store_image_url'
export const STORE_CLEAR = 'store_clear'

// PAYMENT TYPE
export const PAYMENT_TYPES_FETCH = 'payment_types_fetch'
export const SET_STORE_PLANS = 'set_store_plans'
export const HAS_STORE_PLANS = 'has_store_plans'
export const SET_SELECTED_PLAN = 'set_selected_plan'

// COMMON
export const SET_COMMON = 'set_common'
export const CHAT_NOTIFICATION = 'chat_notification'
export const RECEIPT_MAIL_TO = 'receipt_mail_to'
export const RECEIPT_MAIL_SENT = 'receipt_mail_sent'
export const RESET_MAIL_TO = 'reset_mail_to'
export const UPDATE_DRAWER_VISIBILITY = 'update_drawer_visibility'
export const TOGGLE_BILLING_MESSAGE = 'toggle_billing_message'
export const TOGGLE_BLOCK_MANAGE = 'toggle_block_manage'
export const UPDATE_BILLING_UNIQUE_MESSAGES = 'update_billing_unique_messages'
export const RESET_BILLING_UNIQUE_MESSAGES = 'reset_billing_unique_messages'
export const COMMON_START_TOAST = 'common_start_toast'
export const COMMON_STOP_TOAST = 'common_stop_toast'
export const SET_ENABLED_DRAWER_SWIPE = 'set_enabled_drawer_swipe'
export const SHOW_NEED_CONFIGURE_CATALOG_MODAL_FOR_COUPONS = 'show_need_configure_catalog_modal_for_coupons'

// PRINTER
export const PRINTER_SET_DEVICE = 'printer_set_device'
export const PRINTER_SET_DEVICE_PAPER_TYPE = 'printer_set_device_paper_type'
export const PRINTER_SET_DEVICE_TEXT_SIZE = 'printer_set_device_text_size'
export const PRINTER_GET_DEVICE_CONF = 'printer_get_device_conf'
export const PRINTER_SET_REPEAT_NUMBER = 'printer_set_repeat_number'

// MERCADOPAGO
export const MERCADOPAGO_IS_ACTIVATED = 'mercadopago_is_activated'
export const MERCADOPAGO_SET_ERROR_DISPLAYED = 'mercadopago_set_error_displayed'
export const MERCADOPAGO_SET_PROCESSING = 'mercadopago_set_processing'

// FETCH Currency
export const CURRENCY_FETCH = 'currency_fetch'
export const CURRENCY_SET = 'currency_set'

// COMMON
export const COMMON_UPDATE_USER_CHECKED_OPENED_SALES = 'common_update_user_checked_opened_sales'
export const COMMON_START_LOADING = 'common_start_loading'
export const COMMON_STOP_LOADING = 'common_stop_loading'
export const COMMON_START_GLOBAL_LOADING = 'common_start_global_loading'
export const COMMON_STOP_GLOBAL_LOADING = 'common_stop_global_loading'
export const COMMON_USER_REACHED_LIMIT = 'common_user_reached_limit'
export const COMMON_GOTO_CONFIRMATION_SCREEN = 'common_goto_confirmation_screen'
export const COMMON_GOTO_BLOCK_SCREEN = 'common_goto_block_screen'
export const SET_CHECKOUT_PRODUCT_STYLE = 'set_checkout_product_style'
export const COMMON_SET_NOPRODUCTS_HELPER_VISIBILITY = 'common_set_noproducts_helper_visibility'
export const COMMON_SET_FIRSTPRODUCT_HELPER_VISIBILITY = 'common_set_firstproduct_helper_visibility'
export const COMMON_SET_FIRSTSALE_HELPER_VISIBILITY = 'common_set_firstsale_helper_visibility'
export const COMMON_SET_ISONLINE = 'common_set_isonline'
export const SET_INITIAL_ROUTE_NAME = 'set_initial_route_name'
export const SET_ACTUAL_ROUTE_NAME = 'set_actual_route_name'
export const SET_CONCLUSION_STATE = 'set_conclusion_state'
export const CHECKOUT_EDITION_MODE = 'checkout_edition_mode'
export const SET_LAST_DINC = 'set_last_dync'
export const COMMON_SET_VALUES = 'common_set_values'
export const COMMON_REFRESH_CUSTOMER_STATEMENTS = 'common_refresh_customer_statements'
export const COMMON_OPEN_GENERIC_MODAL = 'common_open_generic_modal'
export const COMMON_HIDE_GENERIC_MODAL = 'common_hide_generic_modal'
export const COMMON_SET_LOAD_GENERIC_MODAL = 'common_set_load_generic_modal'
export const COMMON_OPEN_TERMS_MODAL = 'common_open_terms_modal'
export const COMMON_HIDE_TERMS_MODAL = 'common_hide_terms_modal'
export const COMMON_HAS_UPDATED_DEVICE_INFO = 'common_has_update_device_info'
export const COMMON_SET_BARCODE_VISIBILITY = 'common_set_barcode_visibility'
export const COMMON_IS_CANCELLING_SALE = 'common_is_cancelling_sale'
export const COMMON_API_ERROR = 'common_api_error'
export const COMMON_SET_NUMBER_OF_MESSAGES = 'common_set_number_of_messages'
export const COMMON_SET_AUDIO_PERMISSION_REQUESTED = 'common_set_audio_permission_requested'

// USER CONTEXT
export const USER_CONTEXT_FETCH_REQUEST = 'user_context_fetch_request'
export const USER_CONTEXT_FETCH_SUCCESS = 'user_context_fetch_success'
export const USER_CONTEXT_FETCH_FAILURE = 'user_context_fetch_failure'

// SMART ASSISTANT
export const SMART_ASSISTANT_FETCH_SESSIONS_REQUEST = 'smart_assistant_fetch_sessions_request'
export const SMART_ASSISTANT_FETCH_SESSIONS_SUCCESS = 'smart_assistant_fetch_sessions_success'
export const SMART_ASSISTANT_FETCH_SESSIONS_FAILURE = 'smart_assistant_fetch_sessions_failure'

export const SMART_ASSISTANT_CREATE_SESSION_REQUEST = 'smart_assistant_create_session_request'
export const SMART_ASSISTANT_CREATE_SESSION_SUCCESS = 'smart_assistant_create_session_success'
export const SMART_ASSISTANT_CREATE_SESSION_FAILURE = 'smart_assistant_create_session_failure'

export const SMART_ASSISTANT_DELETE_SESSION_REQUEST = 'smart_assistant_delete_session_request'
export const SMART_ASSISTANT_DELETE_SESSION_SUCCESS = 'smart_assistant_delete_session_success'
export const SMART_ASSISTANT_DELETE_SESSION_FAILURE = 'smart_assistant_delete_session_failure'

export const SMART_ASSISTANT_FETCH_SESSION_DETAIL_REQUEST = 'smart_assistant_fetch_session_detail_request'
export const SMART_ASSISTANT_FETCH_SESSION_DETAIL_SUCCESS = 'smart_assistant_fetch_session_detail_success'
export const SMART_ASSISTANT_FETCH_SESSION_DETAIL_FAILURE = 'smart_assistant_fetch_session_detail_failure'

export const SMART_ASSISTANT_CLEAR_SESSION_DETAIL = 'smart_assistant_clear_session_detail'

// USER
export const USER_DETAIL = 'user_detail'
export const USER_ALREADY_SEEN_CATALOG_HELPER = 'user_already_seen_catalog_helper'

// CATALOG
export const SET_CATALOG_COLOR = 'set_catalog_color'
export const SET_INPUT_ERROR_COLOR = 'set_input_error_color'

// STATISTICS
export const STATISTICS_FETCH = 'statistics_fetch'
export const STATISTICS_CLEAR = 'statistics_clear'
export const PERIOD_NAVIGATE = 'period_navigate'
export const PERIOD_TYPE_SET = 'period_type_set'
export const PERIOD_RANGE_SET = 'period_range_set'
export const DATA_TYPE_SET = 'data_type_set'

// PRODUCTS CATEGORIES
export const PRODUCT_CATEGORY_FETCH = 'product_category_fetch'
export const PRODUCT_CATEGORY_GROUP_FETCH = 'product_category_group_fetch'
export const PRODUCT_CATEGORY_CLEAR = 'product_category_clear'
export const PRODUCT_CATEGORY_DETAIL = 'product_category_detail'
export const PRODUCT_CATEGORY_SAVE = 'product_category_save'
export const PRODUCT_CATEGORY_REMOVE = 'product_category_remove'
export const PRODUCT_CATEGORY_CHANGE_QUANTITY = 'product_category_change_quantity'
export const PRODUCT_CATEGORY_SELECT = 'product_category_select'
export const PRODUCT_CATEGORY_SELECT_CLEAN = 'product_category_select_clean'
export const PRODUCT_CATEGORY_REORDER = 'product_category_reorder'

// STOCK
export const STOCK_FETCH = 'stock_fetch'
export const STOCK_SERVER_FETCH = 'stock_server_fetch'
export const STOCK_SERVER_FETCH_ERROR = 'stock_server_fetch_error'
export const STOCK_SET_FILTER = 'stock_set_filter'
export const STOCK_SET_ORDER = 'stock_set_order'
export const STOCK_SET_CATEGORY = 'stock_set_category'
export const STOCK_SET_SEARCH_TEXT = 'stock_set_search_text'
export const STOCK_CLEAR = 'stock_clear'
export const STOCK_CLEAR_FILTER = 'stock_clear_filter'
export const STOCK_FETCH_TOTALS_LOADING = 'stock_fetch_totals_loading'
export const STOCK_FETCH_TOTALS_SUCCESS = 'stock_fetch_totals_success'
export const STOCK_FETCH_TOTALS_ERROR = 'stock_fetch_totals_error'

// BILLING
export const BILLING_FETCH = 'billing_fetch'
export const BILLING_PAYMENT = 'billing_payment'
export const BILLING_SET_SUCCESSFUL_MODAL = 'billing_set_successful_modal'
export const BILLING_SET_ERROR_MODAL = 'billing_set_error_modal'

// INTERNAL
export const INTERNAL_SET_URLS = 'internal_set_urls'
export const INTERNAL_SET_LAST_VERSION = 'internal_set_last_version'
export const INTERNAL_SET_GLOBAL = 'internal_set_global'

// EXTERNAL PAYMENTS
export const EXTERNAL_PAYMENTS_ADD_GATEWAY = 'external_payments_add_gateway'
export const EXTERNAL_PAYMENTS_CLEAR_GATEWAYS = 'external_payments_clear_gateways'
export const EXTERNAL_PAYMENTS_SET_UP = 'external_payments_set_up'
export const EXTERNAL_PAYMENTS_SERVICE_TYPE = 'external_payments_service_type'
export const EXTERNAL_PAYMENTS_COUNTRY_FEES = 'external_payments_country_fees'

// BEHAVIOR
export const BEHAVIOR_FETCH = 'behavior_fetch'

// HELPER - ONBOARDING
export const TOGGLE_HELPER_VISIBILITY = 'toggle_helper_visibility'
export const BUILD_HELPER_STEPS = 'build_helper_steps'
export const SET_HELPER_ACTUAL_STEP = 'set_helper_actual_step'
export const UPDATE_HELPER_STATE = 'update_helper_state'
export const CREATE_HELPER_STATE = 'create_helper_state'
export const HELPER_FETCH = 'helper_fetch'
export const SET_HELPER_REMOTE_AVAILABILITY = 'set_helper_remote_availability'
export const SET_SAMPLE_EXP_INITIAL_SCREEN = 'set_sample_exp_initial_screen'

// FORM
export const SET_FORM = 'set_form'
export const RESET_FORM = 'reset_form'

// VIEWPORT
export const SET_VIEWPORT = 'set_viewport'

// DASHBOARD
export const DASHBOARD_FETCH_STATS = 'dashboard_fetch_stats'
export const DASHBOARD_SET_STATE = 'dashboard_set_state'
export const DASHBOARD_SET_TOTAL_DASHBOARD_VIEWS = 'dashboard_set_total_dashboard_views'
export const DASHBOARD_TOGGLE_VALUES_VISIBILITY = 'dashboard_toggle_values_visibility'
export const DASHBOARD_SET_VERSION = 'dashboard_set_version'

// PROMOTIONS/COUPONS

export const PROMOTION_CREATE = 'promotion_create'
export const PROMOTION_LIST = 'promotion_list'
export const PROMOTION_EDIT = 'promotion_edit'
