import Realm from 'realm'

export class Sale extends Realm.Object {}

Sale.schema = {
	name: 'Sale',

	primaryKey: 'id',
	properties: {
		id: 'string',
		uid: 'string',
		aid: 'string',
		sid: 'string',
		did: 'string',
		number: 'int',
		items: { type: 'list', objectType: 'SaleItem' },
		customer: { type: 'object', objectType: 'SaleCustomer', optional: true },
		payments: { type: 'list', objectType: 'SalePayment' },
		taxes: { type: 'list', objectType: 'SaleTax' },
		dateCreation: 'date',
		dateCreationInt: 'int',
		totalNet: 'double',
		totalGross: 'double',
		totalPay: 'double',
		totalProfit: 'double',
		totalTaxes: 'double',
		payBack: 'double',
		discountValue: 'double',
		discountPercent: 'double',
		status: 'string',
		prevStatus: { type: 'string', optional: true },
		isCancelled: { type: 'bool', default: false },
		isSenderReceipt: { type: 'bool', default: false },
		observation: 'string',
		showObservationInReceipt: { type: 'bool', default: false, optional: true },
		active: { type: 'bool', default: true },
		dateClosed: { type: 'date', optional: true },
		dateClosedInt: { type: 'int', optional: true },
		dateClosedLocal: { type: 'string', optional: true },
		userName: { type: 'string', default: '' },
		userEmail: { type: 'string', default: '' },
		timeline: { type: 'list', objectType: 'SaleTimeline' },
		origin: { type: 'int', default: 0 },
		toDeliver: { type: 'bool', default: false },
		lang: { type: 'string', optional: true },
		currencyCode: { type: 'string', optional: true },
		gatewayKey: { type: 'string', optional: true },
		deviceCountry: { type: 'string', optional: true },
		statusInfo: { type: 'object', objectType: 'SaleStatusInfo', optional: true },
		paymentLink: { type: 'string', optional: true },
		shippingFee: { type: 'object', objectType: 'ShippingFee', optional: true },
		syncStatus: { type: 'string', optional: true },
		generateQRCode: { type: 'bool', default: false, optional: true },
		qrCode: { type: 'string', default: '', optional: true },
		appliedCoupon: { type: 'object', objectType: 'Coupon', optional: true },
		totalCouponDiscount: { type: 'double', optional: true },
		shippingCouponDiscount: { type: 'double', optional: true},
	},
}
