export const CONTENT_HORIZONTAL_SPACING = 20
export const CONTENT_VERTICAL_SPACING = 10
export const CONTENT_BOX_PADDING = 16
export const PHOTO_BUTTON_SIZE = 50
export const PHOTO_BUTTOM_CONTENT_SIZE = 30
